# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cad44204c2d7ef712a95e18e61a0e85233cff20ea077d7a878394540ce18de8e4bbcbf583d507c2c5e1bac0d705266d4db017b3a1a67b0b91e4a1075a5ccecd

test:
  secret_key_base: ba79c09d070f881c3dc724e57255ce10a52e312d5f40a33357541e3ea8ee811ab6404bbbc9e04d01ba98758950d6ad0bcdbc6572217b8a7538ecbb64402916ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
